import {Viewer,Display} from 'three-cad-viewer';
import 'three-cad-viewer/css';
import './style.css';
const L={NEW_FAIL:'新增不满足',FIXED:'已修复',IMPROVED:'改善',REGRESSED:'退化',UNCHANGED:'无变化',NON_COMPARABLE:'不可比较',PASS:'满足',FAIL:'不满足',BLOCKED:'无法执行',REVIEW_REQUIRED:'需复核'};
const S={run:null,selected:null,model:'V2',viewer:null,display:null};
const A=document.querySelector('#app');A.innerHTML=`<header><b>CAD Check</b><span>STEP / OCCT 能力验证 MVP</span><i id="sys"></i></header><nav><button id="run">运行 V1 → V2 校核</button><button id="v1">查看 V1</button><button id="v2">查看 V2</button><span id="rid"></span></nav><section id="sum"></section><main><aside><h3>校核项</h3><div id="cases"></div></aside><section class="viewer"><div class="vh"><span id="vt">真实 STEP 三维视图</span><b id="measure"></b></div><div id="cad"></div></section><aside class="detail"><h3>校核详情</h3><div id="detail">运行校核后查看结果。</div></aside></main>`;
async function api(u,o){const r=await fetch(u,o);if(!r.ok)throw new Error(await r.text());return r.json()}
function cv(){const c=document.querySelector('#cad');c.innerHTML='';S.display=new Display(c,{cadWidth:Math.max(700,c.clientWidth||900),height:620,treeWidth:220,theme:'browser',tools:true,measureTools:false,selectTool:true});S.viewer=new Viewer(S.display,{tools:true},()=>{})}
async function rv(){if(!S.viewer)cv();let u=`/api/models/${S.model}/viewer`;if(S.run&&S.selected)u=`/api/runs/${S.run.run_id}/evidence/${S.selected}/viewer?model=${S.model}`;const p=await api(u);S.viewer.clear?.();S.viewer.render(p.shapes,{ambientIntensity:1,directIntensity:1.1,metalness:.2,roughness:.7,edgeColor:0x606975,defaultOpacity:.85,normalLen:0},{ortho:true,ticks:5,control:'trackball',up:'Z',collapse:1});S.viewer.presetCamera?.('iso')}
function summary(){const c={NEW_FAIL:0,FIXED:0,IMPROVED:0,REGRESSED:0,UNCHANGED:0,NON_COMPARABLE:0};S.run.regression.forEach(x=>c[x.regression]++);document.querySelector('#sum').innerHTML=Object.entries(c).map(([k,v])=>`<div><strong>${v}</strong><span>${L[k]}</span></div>`).join('')}
function list(){document.querySelector('#cases').innerHTML=S.run.regression.map(r=>`<button class="case" data-id="${r.case_id}"><span>${r.title}</span><b>${L[r.regression]}</b></button>`).join('');document.querySelectorAll('.case').forEach(x=>x.onclick=()=>sel(x.dataset.id))}
function sel(id){S.selected=id;const r=S.run.regression.find(x=>x.case_id===id),c=S.run.cases.find(x=>x.id===id);document.querySelector('#measure').textContent=r.candidate.evidence.annotation||'';document.querySelector('#vt').textContent=`${S.model} · ${r.title}`;document.querySelector('#detail').innerHTML=`<h2>${r.title}</h2><p><b>${L[r.regression]}</b></p><p>执行器：${c.executor}</p><p>V1：${r.baseline.value??'—'} ${r.baseline.unit} · ${L[r.baseline.status]}</p><p>V2：${r.candidate.value??'—'} ${r.candidate.unit} · ${L[r.candidate.status]}</p><p>变化量：${r.delta??'—'} ${r.candidate.unit}</p><p>规则来源：${c.source_ref}</p><button id="trace">查看 Trace</button><button id="shot">保存 Evidence PNG</button><pre id="out"></pre>`;document.querySelector('#trace').onclick=async()=>{const t=await fetch(`/api/runs/${S.run.run_id}/trace`).then(x=>x.text());document.querySelector('#out').textContent=t.split('\n').filter(x=>x.includes(`\"case_id\": \"${id}\"`)).join('\n')};document.querySelector('#shot').onclick=async()=>{const im=await S.viewer.getImage('evidence');const o=await api(`/api/runs/${S.run.run_id}/evidence/${id}/screenshot`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({data_url:im.dataUrl})});document.querySelector('#shot').textContent=`已保存 ${o.bytes} bytes`};rv().catch(err=>document.querySelector('#sys').textContent=err.message)}
async function run(){S.run=await api('/api/runs/regression',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({baseline:'V1',candidate:'V2'})});document.querySelector('#rid').textContent=`Run ${S.run.run_id}`;summary();list();sel((S.run.regression.find(x=>x.regression==='NEW_FAIL')||S.run.regression[0]).case_id)}
document.querySelector('#run').onclick=()=>run().catch(e=>document.querySelector('#sys').textContent=e.message);document.querySelector('#v1').onclick=()=>{S.model='V1';rv()};document.querySelector('#v2').onclick=()=>{S.model='V2';rv()};
(async()=>{try{const r=await api('/api/system/readiness');document.querySelector('#sys').textContent=`${r.status} · OCP ${r.python_packages['cadquery-ocp']||'未安装'}`;const m=await api('/api/models');if(!m.V1||!m.V2)throw new Error('请先运行 python tools/prepare_demo.py');await rv()}catch(e){document.querySelector('#sys').textContent=e.message}})();
