import {Display, Viewer} from 'three-cad-viewer';
import 'three-cad-viewer/css';
import './style_v2.css';

const LABELS={MEASURED:'已测量',NEW_FAIL:'新增不满足',FIXED:'已修复',IMPROVED:'改善',REGRESSED:'退化',UNCHANGED:'无变化',NON_COMPARABLE:'不可比较',PASS:'满足',FAIL:'不满足',BLOCKED:'无法执行',REVIEW_REQUIRED:'需复核'};
const state={models:{},cards:[],model:null,mode:'REGRESSION_COMPARE',viewer:null,display:null,viewerReady:false,manifest:null,abort:null,run:null,selected:null,loadedParts:0,totalParts:0,loadedChunks:0,totalChunks:0,streamRoot:null};
const $=(s)=>document.querySelector(s);

async function api(url,options={}){const r=await fetch(url,options);if(!r.ok){let d='';try{d=(await r.json()).detail||r.statusText}catch{d=r.statusText}throw new Error(`${r.status} ${d}`)}return r.json()}
function yieldFrame(){return new Promise(resolve=>requestAnimationFrame(()=>resolve()))}

$('#app').innerHTML=`<div class="shell">
<header class="topbar"><span class="brand">CAD Check</span><select id="model" class="model-select"></select><button id="load" class="load-btn">加载模型</button>
<div class="progress-wrap"><div class="progress-track"><div id="progress" class="progress-fill"></div></div><span id="progress-text" class="progress-text">未加载</span><button id="cancel" class="cancel hidden">取消</button></div>
<details class="more"><summary>更多</summary><div class="more-panel">
<details class="fold"><summary>模型与数据</summary><div class="fold-body"><div class="row"><input id="step-upload" type="file" accept=".stp,.step"><button id="upload-step" class="ghost">上传并加载</button></div><div id="upload-status" class="hint">STEP 导入完成后自动进入模型列表。</div><button id="readiness" class="ghost">查看 Readiness</button><pre id="readiness-out" class="trace hidden"></pre></div></details>
<details class="fold"><summary>工程工具</summary><div id="tool-config" class="fold-body"><span class="hint">按当前模式显示最小配置。</span></div></details>
<details class="fold"><summary>证据与调试</summary><div class="fold-body"><button id="trace-btn" class="ghost">查看 Trace</button><button id="shot-btn" class="ghost">保存当前截图</button><pre id="trace-out" class="trace hidden"></pre></div></details>
</div></details></header>
<nav class="modebar"><button class="mode-tab" data-mode="REGRESSION_COMPARE">版本回归</button><button class="mode-tab" data-mode="ENGINEERING_CHECK">工程校验</button><button class="mode-tab" data-mode="EXPLORE_MEASURE">快速测量</button><button id="run" class="primary mode-action">运行版本回归</button></nav>
<main class="workspace"><aside class="panel"><div class="panel-head"><b>校验结果</b><span id="result-count" class="hint">0</span></div><div id="results" class="result-list"><div class="empty">尚未运行</div></div></aside>
<section class="panel viewer"><div class="viewer-head"><span id="vt">等待加载</span><span class="muted" id="viewer-meta"></span></div><div id="cad" class="cad-host"><div class="empty">选择模型后加载</div></div></section>
<aside class="panel detail"><div class="panel-head"><b>当前校验</b><span id="detail-tag"></span></div><div id="detail" class="detail-body"><div class="empty">选择一条结果</div></div></aside></main></div>`;

function setProgress(pct,text,{indeterminate=false,cancellable=false}={}){const bar=$('#progress');bar.classList.toggle('indeterminate',indeterminate);bar.style.width=indeterminate?'30%':`${Math.max(0,Math.min(100,pct))}%`;$('#progress-text').textContent=text;$('#cancel').classList.toggle('hidden',!cancellable)}
function setMode(mode){state.mode=mode;document.querySelectorAll('.mode-tab').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('#run').textContent=mode==='REGRESSION_COMPARE'?'运行版本回归':mode==='ENGINEERING_CHECK'?'运行工程校验':'运行快速测量';renderToolConfig()}
function ensureViewer(){if(state.viewer)return;const host=$('#cad');host.innerHTML='';state.display=new Display(host,{cadWidth:Math.max(700,host.clientWidth||900),height:Math.max(620,host.clientHeight||620),treeWidth:210,theme:'browser',tools:true,measureTools:false,selectTool:true});state.viewer=new Viewer(state.display,{tools:true},()=>{})}
function clearViewer(){try{state.viewer?.clear?.()}catch{}state.viewer=null;state.display=null;state.viewerReady=false;state.streamRoot=null;$('#cad').innerHTML='<div class="empty">准备加载几何</div>'}
function viewerRenderOptions(){return [{ambientIntensity:1,directIntensity:1.1,metalness:.2,roughness:.7,edgeColor:0x606975,defaultOpacity:.88,normalLen:0},{ortho:true,ticks:5,control:'trackball',up:'Z',collapse:1}]}

async function loadChunk(chunk,index,signal){const payload=await api(chunk.url,{signal});if(!payload?.shapes?.parts?.length)throw new Error(`${chunk.id} 没有可显示几何`);ensureViewer();const [appearance,view]=viewerRenderOptions();if(index===0||!state.viewerReady){state.viewer.render(payload.shapes,appearance,view);state.streamRoot=payload.shapes;state.viewerReady=true;state.viewer.presetCamera?.('iso')}else{let incremental=true;try{for(const part of payload.shapes.parts){state.viewer.addPart(state.streamRoot.id,part)}}catch(error){incremental=false}if(!incremental){state.streamRoot.parts.push(...payload.shapes.parts);state.viewer.clear?.();state.viewer.render(state.streamRoot,appearance,view)}}state.loadedParts+=chunk.part_count;state.loadedChunks+=1;const pct=state.totalParts?Math.round(state.loadedParts/state.totalParts*100):Math.round(state.loadedChunks/state.totalChunks*100);setProgress(pct,`快速网格 ${state.loadedParts}/${state.totalParts} 件`,{cancellable:true});$('#viewer-meta').textContent=`${state.loadedChunks}/${state.totalChunks} 分块`;await yieldFrame()}

async function loadModel(){const model=$('#model').value;if(!model)return;if(state.abort)state.abort.abort();state.abort=new AbortController();clearViewer();state.model=model;$('#vt').textContent=`${model} · 准备中`;setProgress(0,'准备模型…',{indeterminate:true,cancellable:true});try{const manifest=await api(`/api/models/${encodeURIComponent(model)}/viewer/manifest?profile=preview`,{signal:state.abort.signal});state.manifest=manifest;state.loadedParts=0;state.totalParts=manifest.part_count||0;state.loadedChunks=0;state.totalChunks=manifest.chunk_count||0;setProgress(0,`快速网格 0/${state.totalParts} 件`,{cancellable:true});$('#vt').textContent=`${model} · 渐进加载`;for(let i=0;i<manifest.chunks.length;i++){await loadChunk(manifest.chunks[i],i,state.abort.signal)}setProgress(100,`已加载 ${state.totalParts} 件`);$('#vt').textContent=`${model} · 已加载`;$('#viewer-meta').textContent=`${manifest.chunk_count} 分块 · ${manifest.profile.name}`;}catch(error){if(error.name==='AbortError'){setProgress(0,'已取消');$('#vt').textContent=`${model} · 已取消`}else{setProgress(0,'加载失败');$('#vt').textContent=`${model} · 加载失败`;$('#detail').innerHTML=`<p class="hint">${escapeHtml(error.message)}</p>`}}finally{state.abort=null;$('#cancel').classList.add('hidden')}}

function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function currentRows(){if(!state.run)return[];if(state.mode==='REGRESSION_COMPARE'){return(state.run.regression||[]).map(r=>{const e=(state.run.candidate||[]).find(x=>x.case_id===r.case_id)||{};return{caseId:r.case_id,title:e.title||r.case_id,outcome:r.outcome,execution:e}})}const e=state.run.execution;return e?[{caseId:e.case_id,title:e.title,outcome:e.status,execution:e}]:[]}
function renderResults(){const rows=currentRows();$('#result-count').textContent=String(rows.length);$('#results').innerHTML=rows.length?rows.map(r=>`<div class="result ${r.caseId===state.selected?'active':''}" data-case="${escapeHtml(r.caseId)}"><b>${escapeHtml(r.title)}</b><small><span>${escapeHtml(LABELS[r.outcome]||r.outcome)}</span><span>${r.execution?.value??'—'} ${r.execution?.unit??''}</span></small></div>`).join(''):'<div class="empty">暂无结果</div>';document.querySelectorAll('.result').forEach(el=>el.onclick=()=>selectResult(el.dataset.case))}
function renderDetail(row){if(!row){$('#detail').innerHTML='<div class="empty">选择一条结果</div>';$('#detail-tag').innerHTML='';return}const e=row.execution||{};const status=e.status||row.outcome;$('#detail-tag').innerHTML=`<span class="tag ${status==='FAIL'?'fail':status==='PASS'?'pass':''}">${escapeHtml(LABELS[status]||status)}</span>`;$('#detail').innerHTML=`<div class="metric">${e.value??'—'} <small>${escapeHtml(e.unit||'')}</small></div><dl class="kv"><dt>Case</dt><dd>${escapeHtml(row.caseId)}</dd><dt>Executor</dt><dd>${escapeHtml(e.executor||'—')}</dd><dt>Margin</dt><dd>${e.margin??'—'}</dd><dt>Evidence</dt><dd>${escapeHtml(e.evidence?.annotation||'—')}</dd></dl><p class="hint">对象、规则来源与 Trace 收到“更多”中，避免占用主工作区。</p>`}
async function selectResult(caseId){state.selected=caseId;renderResults();const row=currentRows().find(r=>r.caseId===caseId);renderDetail(row);if(!state.run||!row)return;try{setProgress(0,'加载证据…',{indeterminate:true});const model=state.mode==='REGRESSION_COMPARE'?'V2':state.model;const payload=await api(`/api/runs/${state.run.run_id}/evidence/${encodeURIComponent(caseId)}/viewer?model=${encodeURIComponent(model)}`);clearViewer();ensureViewer();const [a,v]=viewerRenderOptions();state.viewer.render(payload.shapes,a,v);state.viewerReady=true;state.viewer.presetCamera?.('iso');$('#vt').textContent=`${model} · ${row.title}`;setProgress(100,'证据已加载')}catch(error){setProgress(0,'证据失败');$('#detail').insertAdjacentHTML('beforeend',`<p class="hint">${escapeHtml(error.message)}</p>`)}}

async function runCurrent(){const button=$('#run');button.disabled=true;try{if(state.mode==='REGRESSION_COMPARE'){state.run=await api('/api/runs/regression',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({baseline:'V1',candidate:'V2'})})}else if(state.mode==='ENGINEERING_CHECK'){const card=$('#tool-card')?.value;if(!card)throw new Error('请选择 Check Card');state.run=await api('/api/runs/check',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:state.model,card_id:card})})}else{const target=$('#tool-a')?.value,counterpart=$('#tool-b')?.value,executor=$('#tool-executor')?.value||'minimum_clearance';if(!target||!counterpart)throw new Error('请选择两个对象');const bindings={bindings:{target:{default:target},counterpart:{default:counterpart}}};state.run=await api('/api/runs/explore',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:state.model,target:'target',counterpart:'counterpart',executor,bindings})})}state.selected=null;renderResults();const first=currentRows()[0];if(first)selectResult(first.caseId)}catch(error){$('#results').innerHTML=`<div class="empty">${escapeHtml(error.message)}</div>`}finally{button.disabled=false}}

async function summaryParts(){if(!state.model)return[];const d=await api(`/api/models/${encodeURIComponent(state.model)}/inventory/summary`);return d.parts||[]}
async function renderToolConfig(){const host=$('#tool-config');if(state.mode==='REGRESSION_COMPARE'){host.innerHTML='<span class="hint">使用 V1 → V2 冻结 Case Set。</span>';return}if(state.mode==='ENGINEERING_CHECK'){host.innerHTML=`<label>Check Card</label><select id="tool-card">${state.cards.map(c=>`<option value="${escapeHtml(c.id)}">${escapeHtml(c.title||c.id)}</option>`).join('')}</select><span class="hint">Binding 沿用当前工程配置。</span>`;return}host.innerHTML='<span class="hint">正在读取对象列表…</span>';try{const parts=await summaryParts();const opts=parts.map(p=>`<option value="${escapeHtml(p.path)}">${escapeHtml(p.name)} · ${escapeHtml(p.path)}</option>`).join('');host.innerHTML=`<label>对象 A</label><select id="tool-a">${opts}</select><label>对象 B</label><select id="tool-b">${opts}</select><label>测量</label><select id="tool-executor"><option value="minimum_clearance">最小间隙</option></select>`}catch(error){host.innerHTML=`<span class="hint">${escapeHtml(error.message)}</span>`}}

async function uploadStep(){const input=$('#step-upload'),file=input.files?.[0];if(!file)return;$('#upload-status').textContent='导入 STEP…';setProgress(0,'导入 STEP…',{indeterminate:true});try{const form=new FormData();form.append('file',file,file.name);const result=await api('/api/models/upload',{method:'POST',body:form});await refreshModels();$('#model').value=result.key;state.model=result.key;$('#upload-status').textContent=`${result.filename} 已登记`;await renderToolConfig();await loadModel()}catch(error){$('#upload-status').textContent=`导入失败：${error.message}`;setProgress(0,'导入失败')}}
async function showReadiness(){if(!state.model)return;const data=await api(`/api/models/${encodeURIComponent(state.model)}/readiness`);const out=$('#readiness-out');out.classList.remove('hidden');out.textContent=JSON.stringify(data,null,2)}
async function showTrace(){if(!state.run?.run_id)return;const r=await fetch(`/api/runs/${state.run.run_id}/trace`);const out=$('#trace-out');out.classList.remove('hidden');out.textContent=await r.text()}
async function saveShot(){if(!state.viewerReady||!state.run?.run_id||!state.selected)return;const image=await state.viewer.getImage('evidence');await api(`/api/runs/${state.run.run_id}/evidence/${encodeURIComponent(state.selected)}/screenshot`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({data_url:image.dataUrl})})}
async function refreshModels(){state.models=await api('/api/models');const select=$('#model');const preferred=state.models.SCANIA?'SCANIA':state.model&&state.models[state.model]?state.model:Object.keys(state.models)[0];select.innerHTML=Object.entries(state.models).map(([k,m])=>`<option value="${escapeHtml(k)}">${escapeHtml(k)} · ${escapeHtml(m.model_id)}</option>`).join('');state.model=preferred;select.value=preferred||'';select.onchange=async()=>{state.model=select.value;clearViewer();setProgress(0,'未加载');$('#vt').textContent=`${state.model} · 等待加载`;await renderToolConfig()}}

$('#load').onclick=loadModel;$('#cancel').onclick=()=>state.abort?.abort();$('#run').onclick=runCurrent;$('#upload-step').onclick=uploadStep;$('#readiness').onclick=showReadiness;$('#trace-btn').onclick=showTrace;$('#shot-btn').onclick=saveShot;document.querySelectorAll('.mode-tab').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));

(async()=>{try{state.cards=await api('/api/check-cards');await refreshModels();setMode('REGRESSION_COMPARE');if(state.model){$('#vt').textContent=`${state.model} · 等待加载`;setProgress(0,'未加载')}}catch(error){setProgress(0,'初始化失败');$('#detail').innerHTML=`<p class="hint">${escapeHtml(error.message)}</p>`}})();
