const S={data:null,filter:'ALL',selected:null};const $=id=>document.getElementById(id);const canvas=$('canvas'),ctx=canvas.getContext('2d');const C={battery:'#355f9e',underbody_bracket:'#73839a',left_rail:'#8b95a7',right_rail:'#8b95a7',motor:'#6e5aa3',motor_bracket:'#7e8d9f',controller:'#2d7b74',controller_bracket:'#7e8d9f',exhaust:'#9a5e4c',front_crossmember:'#697386',ground_ref:'#c8ced8',rear_module:'#6e5aa3'};
async function load(){S.data=await fetch('/api/demo').then(r=>r.json());render();selectCase(S.data.regression.find(x=>x.regression==='NEW_FAIL')?.case_id||S.data.regression[0].case_id)}
function render(){renderSummary();renderFilters();renderList();draw()}
function renderSummary(){const c={TOTAL:S.data.regression.length,NEW_FAIL:0,REGRESSED:0,FIXED:0,IMPROVED:0,UNCHANGED:0};S.data.regression.forEach(r=>c[r.regression]!==undefined&&c[r.regression]++);$('summary').innerHTML=[['TOTAL','Checks'],['NEW_FAIL','New Fail'],['REGRESSED','Regressed'],['FIXED','Fixed'],['IMPROVED','Improved'],['UNCHANGED','Unchanged']].map(([k,l])=>`<div class="metric"><div class="n">${c[k]}</div><div class="l">${l}</div></div>`).join('')}
function renderFilters(){const items=['ALL','NEW_FAIL','REGRESSED','FIXED','IMPROVED','UNCHANGED'];$('filters').innerHTML=items.map(k=>`<button class="filter ${S.filter===k?'active':''}" data-f="${k}">${k}</button>`).join('');document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{S.filter=b.dataset.f;renderFilters();renderList()})}
function renderList(){const rows=S.data.regression.filter(r=>S.filter==='ALL'||r.regression===S.filter);$('caseList').innerHTML=rows.map(r=>`<div class="case ${S.selected===r.case_id?'active':''}" data-id="${r.case_id}"><div class="case-title">${r.title}</div><div class="case-meta"><span>${r.candidate.value??'—'} ${r.candidate.unit}</span><span class="tag ${r.regression}">${r.regression}</span></div></div>`).join('');document.querySelectorAll('.case').forEach(el=>el.onclick=()=>selectCase(el.dataset.id))}
function selectCase(id){S.selected=id;renderList();renderDetail();draw()}
function ruleText(id){const r=S.data.cases.find(x=>x.id===id).rule;return r.operator==='range'?`${r.lower}–${r.upper} ${r.unit}`:`${r.operator} ${r.threshold} ${r.unit}`}
function renderDetail(){const r=S.data.regression.find(x=>x.case_id===S.selected),c=S.data.cases.find(x=>x.id===S.selected);if(!r)return;$('detail').classList.remove('empty');$('detail').innerHTML=`<div class="kicker">${c.executor}</div><h2>${r.title}</h2><span class="tag ${r.regression}">${r.regression}</span><div class="compare"><div class="value-card"><div class="kicker">Baseline V1</div><div class="v">${r.baseline.value??'—'} ${r.baseline.unit}</div><div>${r.baseline.status}</div></div><div class="value-card"><div class="kicker">Candidate V2</div><div class="v">${r.candidate.value??'—'} ${r.candidate.unit}</div><div>${r.candidate.status}</div></div></div><div class="rule"><b>Requirement</b><br>${ruleText(r.case_id)}<br><br><b>Delta</b><br>${r.delta??'—'} ${r.candidate.unit}<br><br><b>Source</b><br>${c.source_ref}</div><div class="actions"><button id="traceBtn" class="secondary">View Trace</button><button id="acceptBtn">Accept</button></div><div class="trace"><b>Evidence</b><br>Focus: ${r.candidate.evidence.focus_ids.join(' ↔ ')}<br>${r.candidate.evidence.annotation}</div>`;$('traceBtn').onclick=()=>{$('traceText').textContent=JSON.stringify({baseline:r.baseline.trace,candidate:r.candidate.trace},null,2);$('traceDialog').showModal()};$('acceptBtn').onclick=e=>{e.target.textContent='Accepted';e.target.disabled=true}}
function resize(){const r=canvas.getBoundingClientRect();canvas.width=Math.max(1,r.width*devicePixelRatio);canvas.height=Math.max(1,r.height*devicePixelRatio);ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}
function project([x,y,z],w,h){return [w/2+(x-y)*.28,h*.66-z*.42+(x+y)*.08]}
function box(b,hi,w,h){const [x,y]=project(b.center,w,h),sx=Math.max(8,b.size[0]*.16),sy=Math.max(8,b.size[1]*.10),sz=Math.max(5,b.size[2]*.22);ctx.save();ctx.translate(x,y);ctx.fillStyle=hi?'#ffcc80':(C[b.id]||'#8a94a6');ctx.strokeStyle=hi?'#d97706':'#596579';ctx.lineWidth=hi?2.5:1;ctx.globalAlpha=b.id==='ground_ref'?.22:.72;ctx.fillRect(-sx/2,-sz/2,sx,sz);ctx.strokeRect(-sx/2,-sz/2,sx,sz);ctx.globalAlpha=.25;ctx.beginPath();ctx.moveTo(-sx/2,-sz/2);ctx.lineTo(-sx/2+sy*.35,-sz/2-sy*.22);ctx.lineTo(sx/2+sy*.35,-sz/2-sy*.22);ctx.lineTo(sx/2,-sz/2);ctx.closePath();ctx.fill();ctx.restore()}
function draw(){if(!S.data)return;resize();const r=canvas.getBoundingClientRect(),w=r.width,h=r.height;ctx.clearRect(0,0,w,h);const sel=S.data.regression.find(x=>x.case_id===S.selected),focus=new Set(sel?.candidate.evidence.focus_ids||[]);Object.values(S.data.models.V2.objects).forEach(b=>box(b,focus.has(b.id),w,h));$('measureLabel').classList.add('hidden');if(sel?.candidate.evidence.line_start&&sel?.candidate.evidence.line_end){const a=project(sel.candidate.evidence.line_start,w,h),b=project(sel.candidate.evidence.line_end,w,h);ctx.strokeStyle='#dc2626';ctx.lineWidth=2;ctx.setLineDash([6,4]);ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke();ctx.setLineDash([]);$('measureLabel').textContent=sel.candidate.evidence.annotation;$('measureLabel').classList.remove('hidden')}$('viewerHint').textContent=sel?sel.title:'Select a case'}
window.addEventListener('resize',draw);$('runBtn').onclick=()=>{$('runBtn').textContent='Running…';setTimeout(()=>{$('runBtn').textContent='Run Verification';render()},450)};load();